-- 反向回滚 knowledge_and_jobs：删除本切片建表的 14 张知识/任务表。
DROP TABLE IF EXISTS document_ingest_idempotencies;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS document_assets;
DROP TABLE IF EXISTS file_tree_nodes;
DROP TABLE IF EXISTS chunk_revisions;
DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS document_chunk_sets;
DROP TABLE IF EXISTS faq_revision_questions;
DROP TABLE IF EXISTS faq_revision_contents;
DROP TABLE IF EXISTS document_revisions;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS knowledge_base_index_generations;
DROP TABLE IF EXISTS knowledge_bases;
DROP TABLE IF EXISTS workspace_source_connections;
