/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedWorkspacesIndexRouteImport } from './routes/_authenticated/workspaces/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedWorkspacesNewRouteImport } from './routes/_authenticated/workspaces/new'
import { Route as AuthenticatedSettingsLanguageRouteImport } from './routes/_authenticated/settings/language'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as authInvitationsTokenRouteImport } from './routes/(auth)/invitations/$token'
import { Route as AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/index'
import { Route as AuthenticatedAdminModelsIndexRouteImport } from './routes/_authenticated/admin/models/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugMembersRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/members'
import { Route as AuthenticatedWorkspacesWorkspaceSlugInvitationsRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/invitations'
import { Route as AuthenticatedAdminModelsProviderIdRouteImport } from './routes/_authenticated/admin/models/$providerId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/api-keys/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugModelsIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/models/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/api-keys/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/models/$providerId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbNewRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/new'
import { Route as AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/jobs/$jobId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/documents/$documentId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/api-keys/new'
import { Route as AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/api-keys/$apiKeyId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/settings'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/search'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/indexes'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/documents/new'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/all'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/route'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/upload'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/new'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/index'
import { Route as AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRouteImport } from './routes/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspacesIndexRoute =
  AuthenticatedWorkspacesIndexRouteImport.update({
    id: '/workspaces/',
    path: '/workspaces/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedWorkspacesNewRoute =
  AuthenticatedWorkspacesNewRouteImport.update({
    id: '/workspaces/new',
    path: '/workspaces/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLanguageRoute =
  AuthenticatedSettingsLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const authInvitationsTokenRoute = authInvitationsTokenRouteImport.update({
  id: '/(auth)/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesWorkspaceSlugRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport.update({
    id: '/workspaces/$workspaceSlug',
    path: '/workspaces/$workspaceSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedAdminModelsIndexRoute =
  AuthenticatedAdminModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugMembersRoute =
  AuthenticatedWorkspacesWorkspaceSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute =
  AuthenticatedWorkspacesWorkspaceSlugInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedAdminModelsProviderIdRoute =
  AuthenticatedAdminModelsProviderIdRouteImport.update({
    id: '/models/$providerId',
    path: '/models/$providerId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbIndexRouteImport.update({
    id: '/kb/',
    path: '/kb/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRouteImport.update({
    id: '/models/$providerId',
    path: '/models/$providerId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbNewRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbNewRouteImport.update({
    id: '/kb/new',
    path: '/kb/new',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute =
  AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRouteImport.update({
    id: '/$apiKeyId',
    path: '/$apiKeyId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteImport.update({
    id: '/kb/$kbId',
    path: '/kb/$kbId',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRouteImport.update({
    id: '/indexes',
    path: '/indexes',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteImport.update(
    {
      id: '/files',
      path: '/files',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRouteImport.update({
    id: '/web/',
    path: '/web/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRouteImport.update({
    id: '/faq/',
    path: '/faq/',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRouteImport.update(
    {
      id: '/web/$documentId',
      path: '/web/$documentId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRouteImport.update(
    {
      id: '/upload',
      path: '/upload',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRouteImport.update(
    {
      id: '/$documentId',
      path: '/$documentId',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRouteImport.update({
    id: '/faq/new',
    path: '/faq/new',
    getParentRoute: () =>
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
  } as any)
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRouteImport.update(
    {
      id: '/faq/$documentId/',
      path: '/faq/$documentId/',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
    } as any,
  )
const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRouteImport.update(
    {
      id: '/faq/$documentId/edit',
      path: '/faq/$documentId/edit',
      getParentRoute: () =>
        AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/invitations/$token': typeof authInvitationsTokenRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/workspaces/new': typeof AuthenticatedWorkspacesNewRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/workspaces/$workspaceSlug/api-keys': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteWithChildren
  '/admin/models/$providerId': typeof AuthenticatedAdminModelsProviderIdRoute
  '/workspaces/$workspaceSlug/invitations': typeof AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute
  '/workspaces/$workspaceSlug/members': typeof AuthenticatedWorkspacesWorkspaceSlugMembersRoute
  '/admin/models/': typeof AuthenticatedAdminModelsIndexRoute
  '/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteWithChildren
  '/workspaces/$workspaceSlug/api-keys/$apiKeyId': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute
  '/workspaces/$workspaceSlug/api-keys/new': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute
  '/workspaces/$workspaceSlug/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute
  '/workspaces/$workspaceSlug/jobs/$jobId': typeof AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute
  '/workspaces/$workspaceSlug/kb/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbNewRoute
  '/workspaces/$workspaceSlug/models/$providerId': typeof AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute
  '/workspaces/$workspaceSlug/api-keys/': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute
  '/workspaces/$workspaceSlug/kb/': typeof AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute
  '/workspaces/$workspaceSlug/models/': typeof AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteWithChildren
  '/workspaces/$workspaceSlug/kb/$kbId/indexes': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute
  '/workspaces/$workspaceSlug/kb/$kbId/search': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute
  '/workspaces/$workspaceSlug/kb/$kbId/settings': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute
  '/workspaces/$workspaceSlug/kb/$kbId/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteWithChildren
  '/workspaces/$workspaceSlug/kb/$kbId/content/all': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute
  '/workspaces/$workspaceSlug/kb/$kbId/documents/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files/upload': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/web/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/invitations/$token': typeof authInvitationsTokenRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/workspaces/new': typeof AuthenticatedWorkspacesNewRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/workspaces': typeof AuthenticatedWorkspacesIndexRoute
  '/admin/models/$providerId': typeof AuthenticatedAdminModelsProviderIdRoute
  '/workspaces/$workspaceSlug/invitations': typeof AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute
  '/workspaces/$workspaceSlug/members': typeof AuthenticatedWorkspacesWorkspaceSlugMembersRoute
  '/admin/models': typeof AuthenticatedAdminModelsIndexRoute
  '/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/workspaces/$workspaceSlug/api-keys/$apiKeyId': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute
  '/workspaces/$workspaceSlug/api-keys/new': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute
  '/workspaces/$workspaceSlug/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute
  '/workspaces/$workspaceSlug/jobs/$jobId': typeof AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute
  '/workspaces/$workspaceSlug/kb/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbNewRoute
  '/workspaces/$workspaceSlug/models/$providerId': typeof AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute
  '/workspaces/$workspaceSlug/api-keys': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute
  '/workspaces/$workspaceSlug/kb': typeof AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute
  '/workspaces/$workspaceSlug/models': typeof AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/indexes': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute
  '/workspaces/$workspaceSlug/kb/$kbId/search': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute
  '/workspaces/$workspaceSlug/kb/$kbId/settings': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute
  '/workspaces/$workspaceSlug/kb/$kbId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/all': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute
  '/workspaces/$workspaceSlug/kb/$kbId/documents/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files/upload': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/files': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/web': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute
  '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/workspaces/$workspaceSlug': typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  '/(auth)/invitations/$token': typeof authInvitationsTokenRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/language': typeof AuthenticatedSettingsLanguageRoute
  '/_authenticated/workspaces/new': typeof AuthenticatedWorkspacesNewRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/workspaces/': typeof AuthenticatedWorkspacesIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/api-keys': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteWithChildren
  '/_authenticated/admin/models/$providerId': typeof AuthenticatedAdminModelsProviderIdRoute
  '/_authenticated/workspaces/$workspaceSlug/invitations': typeof AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute
  '/_authenticated/workspaces/$workspaceSlug/members': typeof AuthenticatedWorkspacesWorkspaceSlugMembersRoute
  '/_authenticated/admin/models/': typeof AuthenticatedAdminModelsIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/': typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug/api-keys/$apiKeyId': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute
  '/_authenticated/workspaces/$workspaceSlug/api-keys/new': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute
  '/_authenticated/workspaces/$workspaceSlug/documents/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute
  '/_authenticated/workspaces/$workspaceSlug/jobs/$jobId': typeof AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbNewRoute
  '/_authenticated/workspaces/$workspaceSlug/models/$providerId': typeof AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute
  '/_authenticated/workspaces/$workspaceSlug/api-keys/': typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/': typeof AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/models/': typeof AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/indexes': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/search': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/settings': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteWithChildren
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/all': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/documents/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/new': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/upload': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute
  '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/': typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/setup'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/workspaces/$workspaceSlug'
    | '/invitations/$token'
    | '/settings/appearance'
    | '/settings/language'
    | '/workspaces/new'
    | '/settings/'
    | '/workspaces/'
    | '/workspaces/$workspaceSlug/api-keys'
    | '/admin/models/$providerId'
    | '/workspaces/$workspaceSlug/invitations'
    | '/workspaces/$workspaceSlug/members'
    | '/admin/models/'
    | '/workspaces/$workspaceSlug/'
    | '/workspaces/$workspaceSlug/kb/$kbId'
    | '/workspaces/$workspaceSlug/api-keys/$apiKeyId'
    | '/workspaces/$workspaceSlug/api-keys/new'
    | '/workspaces/$workspaceSlug/documents/$documentId'
    | '/workspaces/$workspaceSlug/jobs/$jobId'
    | '/workspaces/$workspaceSlug/kb/new'
    | '/workspaces/$workspaceSlug/models/$providerId'
    | '/workspaces/$workspaceSlug/api-keys/'
    | '/workspaces/$workspaceSlug/kb/'
    | '/workspaces/$workspaceSlug/models/'
    | '/workspaces/$workspaceSlug/kb/$kbId/content'
    | '/workspaces/$workspaceSlug/kb/$kbId/indexes'
    | '/workspaces/$workspaceSlug/kb/$kbId/search'
    | '/workspaces/$workspaceSlug/kb/$kbId/settings'
    | '/workspaces/$workspaceSlug/kb/$kbId/'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/all'
    | '/workspaces/$workspaceSlug/kb/$kbId/documents/new'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/new'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files/upload'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files/'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/web/'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/setup'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/invitations/$token'
    | '/settings/appearance'
    | '/settings/language'
    | '/workspaces/new'
    | '/settings'
    | '/workspaces'
    | '/admin/models/$providerId'
    | '/workspaces/$workspaceSlug/invitations'
    | '/workspaces/$workspaceSlug/members'
    | '/admin/models'
    | '/workspaces/$workspaceSlug'
    | '/workspaces/$workspaceSlug/api-keys/$apiKeyId'
    | '/workspaces/$workspaceSlug/api-keys/new'
    | '/workspaces/$workspaceSlug/documents/$documentId'
    | '/workspaces/$workspaceSlug/jobs/$jobId'
    | '/workspaces/$workspaceSlug/kb/new'
    | '/workspaces/$workspaceSlug/models/$providerId'
    | '/workspaces/$workspaceSlug/api-keys'
    | '/workspaces/$workspaceSlug/kb'
    | '/workspaces/$workspaceSlug/models'
    | '/workspaces/$workspaceSlug/kb/$kbId/indexes'
    | '/workspaces/$workspaceSlug/kb/$kbId/search'
    | '/workspaces/$workspaceSlug/kb/$kbId/settings'
    | '/workspaces/$workspaceSlug/kb/$kbId'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/all'
    | '/workspaces/$workspaceSlug/kb/$kbId/documents/new'
    | '/workspaces/$workspaceSlug/kb/$kbId/content'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/new'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files/upload'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/files'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/web'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit'
    | '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/(auth)/setup'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/workspaces/$workspaceSlug'
    | '/(auth)/invitations/$token'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/language'
    | '/_authenticated/workspaces/new'
    | '/_authenticated/settings/'
    | '/_authenticated/workspaces/'
    | '/_authenticated/workspaces/$workspaceSlug/api-keys'
    | '/_authenticated/admin/models/$providerId'
    | '/_authenticated/workspaces/$workspaceSlug/invitations'
    | '/_authenticated/workspaces/$workspaceSlug/members'
    | '/_authenticated/admin/models/'
    | '/_authenticated/workspaces/$workspaceSlug/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId'
    | '/_authenticated/workspaces/$workspaceSlug/api-keys/$apiKeyId'
    | '/_authenticated/workspaces/$workspaceSlug/api-keys/new'
    | '/_authenticated/workspaces/$workspaceSlug/documents/$documentId'
    | '/_authenticated/workspaces/$workspaceSlug/jobs/$jobId'
    | '/_authenticated/workspaces/$workspaceSlug/kb/new'
    | '/_authenticated/workspaces/$workspaceSlug/models/$providerId'
    | '/_authenticated/workspaces/$workspaceSlug/api-keys/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/'
    | '/_authenticated/workspaces/$workspaceSlug/models/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/indexes'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/search'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/settings'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/all'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/documents/new'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/new'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/upload'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit'
    | '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSetupRoute: typeof authSetupRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  authInvitationsTokenRoute: typeof authInvitationsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/': {
      id: '/_authenticated/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof AuthenticatedWorkspacesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/workspaces/new': {
      id: '/_authenticated/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/language': {
      id: '/_authenticated/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AuthenticatedSettingsLanguageRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/(auth)/invitations/$token': {
      id: '/(auth)/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof authInvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces/$workspaceSlug': {
      id: '/_authenticated/workspaces/$workspaceSlug'
      path: '/workspaces/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/': {
      id: '/_authenticated/workspaces/$workspaceSlug/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/admin/models/': {
      id: '/_authenticated/admin/models/'
      path: '/models'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AuthenticatedAdminModelsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/members': {
      id: '/_authenticated/workspaces/$workspaceSlug/members'
      path: '/members'
      fullPath: '/workspaces/$workspaceSlug/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugMembersRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/invitations': {
      id: '/_authenticated/workspaces/$workspaceSlug/invitations'
      path: '/invitations'
      fullPath: '/workspaces/$workspaceSlug/invitations'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInvitationsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/admin/models/$providerId': {
      id: '/_authenticated/admin/models/$providerId'
      path: '/models/$providerId'
      fullPath: '/admin/models/$providerId'
      preLoaderRoute: typeof AuthenticatedAdminModelsProviderIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/api-keys': {
      id: '/_authenticated/workspaces/$workspaceSlug/api-keys'
      path: '/api-keys'
      fullPath: '/workspaces/$workspaceSlug/api-keys'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/models/': {
      id: '/_authenticated/workspaces/$workspaceSlug/models/'
      path: '/models'
      fullPath: '/workspaces/$workspaceSlug/models/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugModelsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/'
      path: '/kb'
      fullPath: '/workspaces/$workspaceSlug/kb/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/api-keys/': {
      id: '/_authenticated/workspaces/$workspaceSlug/api-keys/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/api-keys/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/models/$providerId': {
      id: '/_authenticated/workspaces/$workspaceSlug/models/$providerId'
      path: '/models/$providerId'
      fullPath: '/workspaces/$workspaceSlug/models/$providerId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/new': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/new'
      path: '/kb/new'
      fullPath: '/workspaces/$workspaceSlug/kb/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbNewRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/jobs/$jobId': {
      id: '/_authenticated/workspaces/$workspaceSlug/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/workspaces/$workspaceSlug/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/documents/$documentId': {
      id: '/_authenticated/workspaces/$workspaceSlug/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/workspaces/$workspaceSlug/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/api-keys/new': {
      id: '/_authenticated/workspaces/$workspaceSlug/api-keys/new'
      path: '/new'
      fullPath: '/workspaces/$workspaceSlug/api-keys/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/api-keys/$apiKeyId': {
      id: '/_authenticated/workspaces/$workspaceSlug/api-keys/$apiKeyId'
      path: '/$apiKeyId'
      fullPath: '/workspaces/$workspaceSlug/api-keys/$apiKeyId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId'
      path: '/kb/$kbId'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/settings': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/settings'
      path: '/settings'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/settings'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/search': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/search'
      path: '/search'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/search'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/indexes': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/indexes'
      path: '/indexes'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/indexes'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content'
      path: '/content'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/documents/new': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/documents/new'
      path: '/documents/new'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/documents/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/all': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/all'
      path: '/all'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/all'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files'
      path: '/files'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/files'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/'
      path: '/web'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/web/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/'
      path: '/'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/files/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/'
      path: '/faq'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/faq/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId'
      path: '/web/$documentId'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/web/$documentId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/upload': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/upload'
      path: '/upload'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/files/upload'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId'
      path: '/$documentId'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/files/$documentId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/new': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/new'
      path: '/faq/new'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/faq/new'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/'
      path: '/faq/$documentId'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
    '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit': {
      id: '/_authenticated/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit'
      path: '/faq/$documentId/edit'
      fullPath: '/workspaces/$workspaceSlug/kb/$kbId/content/faq/$documentId/edit'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRouteImport
      parentRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminModelsProviderIdRoute: typeof AuthenticatedAdminModelsProviderIdRoute
  AuthenticatedAdminModelsIndexRoute: typeof AuthenticatedAdminModelsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminModelsProviderIdRoute:
      AuthenticatedAdminModelsProviderIdRoute,
    AuthenticatedAdminModelsIndexRoute: AuthenticatedAdminModelsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsLanguageRoute: typeof AuthenticatedSettingsLanguageRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsLanguageRoute: AuthenticatedSettingsLanguageRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute
  AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute
  AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugApiKeysApiKeyIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute:
      AuthenticatedWorkspacesWorkspaceSlugApiKeysNewRoute,
    AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugApiKeysIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesDocumentIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesUploadRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFilesRouteRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentAllRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqNewRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebDocumentIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentWebIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdEditRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentFaqDocumentIdIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute
}

const AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdContentRouteRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexesRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdSearchRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdSettingsRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdDocumentsNewRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteChildren,
  )

interface AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren {
  AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute: typeof AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute
  AuthenticatedWorkspacesWorkspaceSlugMembersRoute: typeof AuthenticatedWorkspacesWorkspaceSlugMembersRoute
  AuthenticatedWorkspacesWorkspaceSlugIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute
  AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute
  AuthenticatedWorkspacesWorkspaceSlugKbNewRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbNewRoute
  AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute: typeof AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute
  AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute
  AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute: typeof AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute
}

const AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren: AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugApiKeysRouteRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute:
      AuthenticatedWorkspacesWorkspaceSlugInvitationsRoute,
    AuthenticatedWorkspacesWorkspaceSlugMembersRoute:
      AuthenticatedWorkspacesWorkspaceSlugMembersRoute,
    AuthenticatedWorkspacesWorkspaceSlugIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbKbIdRouteRouteWithChildren,
    AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugDocumentsDocumentIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugJobsJobIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbNewRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbNewRoute,
    AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute:
      AuthenticatedWorkspacesWorkspaceSlugModelsProviderIdRoute,
    AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugKbIndexRoute,
    AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute:
      AuthenticatedWorkspacesWorkspaceSlugModelsIndexRoute,
  }

const AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren =
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute._addFileChildren(
    AuthenticatedWorkspacesWorkspaceSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute: typeof AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren
  AuthenticatedWorkspacesNewRoute: typeof AuthenticatedWorkspacesNewRoute
  AuthenticatedWorkspacesIndexRoute: typeof AuthenticatedWorkspacesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedWorkspacesWorkspaceSlugRouteRoute:
    AuthenticatedWorkspacesWorkspaceSlugRouteRouteWithChildren,
  AuthenticatedWorkspacesNewRoute: AuthenticatedWorkspacesNewRoute,
  AuthenticatedWorkspacesIndexRoute: AuthenticatedWorkspacesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSetupRoute: authSetupRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  authInvitationsTokenRoute: authInvitationsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
